### ISSUE TITLE
Error: "NameID value not set" after login

### ISSUE THREAD

**Issue by lucascudo** [kingstarter/laravel-saml#17]
Hello,

I am aparently facing same problem described at https://github.com/kingstarter/laravel-saml/issues/12 and https://github.com/kingstarter/laravel-saml/issues/15 , wondering if someone has figured out how to resolve that?

**Comment by mukk85** [comment]
I am also getting this when the NameIDPolicy is set to urn:oasis:names:tc:SAML:2.0:nameid-format:transient, could this be an issue with using SAML 2?

**Comment by mukk85** [comment]
What was the issue/solution? I ended up commenting out that check and it seems to work, but probably not ideal.

**Comment by robverhoef** [comment]
I am facing this issue too. 

> LightSamlModelException: NameID value not set

I can't figure out where the problem is.
I have 2 service providers with nearly identical configs. One works (destination https://sptest.iamshowcase.com/acs) , the other one doesn't.
Both configs have: 

> 'nameID' => 'email'

This request is working:
`<samlp:AuthnRequest 
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" 
    ForceAuthn="false" 
    ID="ab9625f3fa1286566ae35108319fc0d9b7e602beb" 
    IssueInstant="2019-04-06T14:51:37Z" 
    Destination="[my login url]" 
    AssertionConsumerServiceURL="https://sptest.iamshowcase.com/acs"  
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"   
    Version="2.0">
    <saml:Issuer>IAMShowcase</saml:Issuer>
</samlp:AuthnRequest>`

This one doesn't:
`<samlp:AuthnRequest 
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" 
    ID="_69e6929c04e5181bef97fb5dac543adc007242aa4f" 
    Version="2.0" 
    IssueInstant="2019-04-06T12:33:25Z" 
    Destination="[my login url]" 
    AssertionConsumerServiceURL="[my clients url]" 
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
    <saml:Issuer>[my clients url]</saml:Issuer>
    <samlp:NameIDPolicy 
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" 
        AllowCreate="true"/>
</samlp:AuthnRequest>`

Obviously they share the same metadata.xml. And I'm not sure if this is relevant, but my metadata.xml contains:
`<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>`

I would be would be really grateful if somebody could point me in the right direction.
